version: '3.1'

services:

  wordpress:
    image: wordpress:php7.4-fpm-alpine
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wpC1234
      WORDPRESS_DB_NAME: db-wordpress
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: db-wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wpC1234
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db: